# Generated by Django 5.1.5 on 2025-02-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked_in'), ('CHECKED_OUT', 'Checked_out'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50),
        ),
    ]
